name: gtk-locales-example
version: '0.1'
summary: Example of using the 'gtk-locales' library
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.
grade: devel
confinement: devmode

base: core18

### START part
parts:
  gtk-locales:
    after: [my-part] # Make this part run last
    plugin: nil
    build-packages:
      - apt
      - dpkg
    override-pull: |
      set -eux
      apt download "language-pack-gnome-*-base"
    override-build: |
      set -eux
      for deb in *.deb; do dpkg-deb -x $deb .; done
      find usr/share/locale-langpack -type f -not -name "gtk30*.mo" -exec rm '{}' \;
      mkdir -p "$SNAPCRAFT_PART_INSTALL/usr/share"
      cp -R usr/share/locale-langpack "$SNAPCRAFT_PART_INSTALL/usr/share/"
### END part

  my-part:
    plugin: nil
